server:
  port: 5000
spring:
  application:
    name: desafio
  datasource:
    url: jdbc:mysql://localhost/desafio
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: desafio
    password: desafio
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
management:
  metrics:
    tags:
      application: ${spring.application.name}
    context-path: /actuator
    server:
      port: 9090